name: buildfork 
on: 
  push: 
    branches: 
      - main 
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    needs: build 
    environment: 
      name: production 
      url: http://obedient-low.surge.sh
    steps: 
      - name: Download the Build Artifact 
        uses: actions/download-artifact@v4.1.9 
        with: 
          name: build
      - name: deploy to surge 
        run: npx surge --project ‘.’ --domain http://obedient-low.surge.sh 
        env: 
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }} 
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4.2.0
      - name: Cache 
        uses: actions/cache@v4.2.2 
        with: 
          path: ~/.npm 
          key: buildCache
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload code coverage 
        uses: actions/upload-artifact@v4.6.1 
        with: 
          name: codecoverage 
          path: coverage
      - name: build 
        run: npm run build 
      - name: Upload build files 
        uses: actions/upload-artifact@v4.6.1 
        with: 
          name: build 
          path: build 
